CREATE TABLE board_game
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    barcode            VARCHAR(255)                            NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    notes              VARCHAR(255),
    quantity           INTEGER                                 NOT NULL,
    quantity_available INTEGER                                 NOT NULL,
    event_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_boardgame PRIMARY KEY (id)
);

CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE overseer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    surname  VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_overseer PRIMARY KEY (id)
);

CREATE TABLE overseer_event
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    permissions_type VARCHAR(255),
    overseer_id      BIGINT                                  NOT NULL,
    event_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_overseerevent PRIMARY KEY (id)
);

CREATE TABLE rent
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    returned      BOOLEAN                                 NOT NULL,
    renter_id     BIGINT                                  NOT NULL,
    board_game_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_rent PRIMARY KEY (id)
);

CREATE TABLE renter
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    barcode   VARCHAR(255)                            NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    event_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_renter PRIMARY KEY (id)
);

ALTER TABLE overseer_event
    ADD CONSTRAINT uc_29cc03a8361e10a3f892419fb UNIQUE (overseer_id, event_id);

ALTER TABLE board_game
    ADD CONSTRAINT FK_BOARDGAME_ON_EVENTID FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE overseer_event
    ADD CONSTRAINT FK_OVERSEEREVENT_ON_EVENTID FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE overseer_event
    ADD CONSTRAINT FK_OVERSEEREVENT_ON_OVERSEERID FOREIGN KEY (overseer_id) REFERENCES overseer (id);

ALTER TABLE renter
    ADD CONSTRAINT FK_RENTER_ON_EVENTID FOREIGN KEY (event_id) REFERENCES event (id);

ALTER TABLE rent
    ADD CONSTRAINT FK_RENT_ON_BOARDGAMEID FOREIGN KEY (board_game_id) REFERENCES board_game (id);

ALTER TABLE rent
    ADD CONSTRAINT FK_RENT_ON_RENTERID FOREIGN KEY (renter_id) REFERENCES renter (id);